In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [3]:
df = pd.read_csv("netflix_titles.csv")
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [5]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [6]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [7]:
df[df["duration"].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [8]:
df_clean = df.copy()

In [10]:
mask = df_clean["duration"].isna() & df_clean["rating"].str.fullmatch(r"\d+ min", na=False)

In [11]:
df_clean[mask]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [12]:
df_clean.loc[mask, "duration"] = df_clean.loc[mask, "rating"]

In [13]:
df_clean.loc[mask, "rating"] = pd.NA

In [14]:
df_clean.loc[mask, ["title", "rating", "duration"]]

                                     title rating duration
5541                       Louis C.K. 2017   <NA>   74 min
5794                 Louis C.K.: Hilarious   <NA>   84 min
5813  Louis C.K.: Live at the Comedy Store   <NA>   66 min

In [15]:
df_clean[["rating", "duration"]].isna().sum()

rating      7
duration    0
dtype: int64

In [16]:
df_clean["rating"].value_counts(dropna=False)

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NaN            4
NC-17          3
<NA>           3
UR             3
Name: count, dtype: int64

In [17]:
df_clean["rating"] = df_clean["rating"].astype("string")

In [18]:
df_clean["rating"].value_counts(dropna=False).sum()

np.int64(8807)

In [19]:
df_clean.groupby("type")["director"].apply(lambda column: column.isna().sum())

type
Movie       188
TV Show    2446
Name: director, dtype: int64

In [20]:
df_clean.loc[df_clean["cast"].isna(), ["title", "type", "listed_in"]].head(10)

,title,type,listed_in
0,Dick Johnson Is Dead,Movie,Documentaries
3,Jailbirds New Orleans,TV Show,"Docuseries, Reality TV"
10,"Vendetta: Truth, Lies and The Mafia",TV Show,"Crime TV Shows, Docuseries, International TV S..."
14,Crime Stories: India Detectives,TV Show,"British TV Shows, Crime TV Shows, Docuseries"
16,Europe's Most Dangerous Man: Otto Skorzeny in ...,Movie,"Documentaries, International Movies"
20,Monsters Inside: The 24 Faces of Billy Milligan,TV Show,"Crime TV Shows, Docuseries, International TV S..."
45,My Heroes Were Cowboys,Movie,Documentaries
66,Raja Rasoi Aur Anya Kahaniyan,TV Show,"Docuseries, International TV Shows"
69,Stories by Rabindranath Tagore,TV Show,"International TV Shows, TV Dramas"
74,The World's Most Amazing Vacation Rentals,TV Show,Reality TV

In [22]:
df_clean.loc[df_clean["country"].isna(), ["title", "type", "country"]].head(10)

                                                title     type country
2                                           Ganglands  TV Show     NaN
3                               Jailbirds New Orleans  TV Show     NaN
5                                       Midnight Mass  TV Show     NaN
6                    My Little Pony: A New Generation    Movie     NaN
10                Vendetta: Truth, Lies and The Mafia  TV Show     NaN
11                                   Bangkok Breaking  TV Show     NaN
13                   Confessions of an Invisible Girl    Movie     NaN
14                    Crime Stories: India Detectives  TV Show     NaN
16  Europe's Most Dangerous Man: Otto Skorzeny in ...    Movie     NaN
18                                          Intrusion    Movie     NaN

In [23]:
df_clean.loc[df_clean["date_added"].isna(), ["title", "date_added", "release_year"]]

                                            title date_added  release_year
6066  A Young Doctor's Notebook and Other Stories        NaN          2013
6174              Anthony Bourdain: Parts Unknown        NaN          2018
6795                                      Frasier        NaN          2003
6806                                      Friends        NaN          2003
6901                              Gunslinger Girl        NaN          2008
7196                                     Kikoriki        NaN          2010
7254                          La Familia P. Luche        NaN          2012
7406                                        Maron        NaN          2016
7847                                 Red vs. Blue        NaN          2015
8182                 The Adventures of Figaro Pho        NaN          2015

In [24]:
df_clean["date_added"] = pd.to_datetime(
    df_clean["date_added"].str.strip(),
    format="%B %d, %Y"
)

In [25]:
df_clean["date_added"].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

In [27]:
df_clean["date_added"].isna().sum()

np.int64(10)

In [28]:
df_clean["duration"].str.split(" ", n=1, expand=True).head()

    0        1
0  90      min
1   2  Seasons
2   1   Season
3   1   Season
4   2  Seasons

In [29]:
df_clean[["duration_value", "duration_unit"]] = (
    df_clean["duration"].str.split(" ", n=1, expand=True)
)

In [30]:
df_clean[["duration", "duration_value", "duration_unit"]].head()

    duration duration_value duration_unit
0     90 min             90           min
1  2 Seasons              2       Seasons
2   1 Season              1        Season
3   1 Season              1        Season
4  2 Seasons              2       Seasons

In [31]:
df_clean["duration_value"] = df_clean["duration_value"].astype("Int64")

In [32]:
df_clean["duration_unit"] = df_clean["duration_unit"].replace({
    "Season": "season",
    "Seasons": "season"
})

In [33]:
df_clean[["duration_value", "duration_unit"]].head()

   duration_value duration_unit
0              90           min
1               2        season
2               1        season
3               1        season
4               2        season

In [34]:
df_clean.duplicated().sum()

np.int64(0)

In [35]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8807 non-null   object
 1   type            8807 non-null   object
 2   title           8807 non-null   object
 3   director        6173 non-null   object
 4   cast            7982 non-null   object
 5   country         7976 non-null   object
 6   date_added      8797 non-null   datetime64[ns]
 7   release_year    8807 non-null   int64
 8   rating          8800 non-null   string
 9   duration        8807 non-null   object
 10  listed_in       8807 non-null   object
 11  description     8807 non-null   object
 12  duration_value  8807 non-null   Int64
 13  duration_unit   8807 non-null   object
dtypes: Int64(1), datetime64[ns](1), int64(1), object(10), string(1)
memory usage: 972.0+ KB

In [36]:
df_clean.to_csv("netflix_titles_cleaned.csv", index=False)

-Moved three duration values from rating to duration
-Kept unkown director, cast, country,rating and date -values missing rather that guessing
-ConVERTED dare_added to datetime
-Split duration into a whole-number value and a consistent unit
-Found no exact duplicate rows
-Retained all 8807 records and exported 14 columns